apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "HELM.fullname" . }}-hpa-fastapi
  labels:
  {{- include "HELM.labels" . | nindent 4 }}
spec:
  maxReplicas: 6
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastapi-deployment
  targetCPUUtilizationPercentage: 70
